spring:
    datasource:
        url: jdbc:h2:tcp://localhost/C:/xuebiao/h2db/test
        driver-class-name: org.h2.Driver
        username: sa
        password: 123456
server:
    port: 8888
    servlet:
        context-path: /helloworld
logging:
    path: ./log/
